version: '2'

services:
 guacamole-client:
  extends:
   file: ./docker-compose.yml
   service: guacamole-client
  image: nanocloud/guacamole-client

 guacamole-server:
  extends:
   file: ./docker-compose.yml
   service: guacamole-server
  build: ./guacd
  image: nanocloud/guacamole-server

 nanocloud-backend:
  extends:
   file: ./docker-compose.yml
   service: nanocloud-backend
  volumes_from:
   - nanocloud-frontend
  image: nanocloud/nanocloud-backend

 nanocloud-frontend:
  extends:
   file: ./docker-compose.yml
   service: nanocloud-frontend
  volumes:
   - /opt/front
  container_name: "nanocloud-frontend"
  image: nanocloud/nanocloud-frontend

 proxy:
  extends:
   file: ./docker-compose.yml
   service: proxy
  image: nanocloud/proxy

 postgres:
  extends:
   file: ./docker-compose.yml
   service: postgres

 iaas-module:
  extends:
   file: ./docker-compose.yml
   service: iaas-module
  image: nanocloud/iaas-module

networks:
 nanocloud:
  driver: bridge
