FROM nanocloud/iaas-module
MAINTAINER \
  Olivier Berthonneau <olivier.berthonneau@nanocloud.com>

ENV GOBIN $GOPATH/bin
RUN go get github.com/githubnemo/CompileDaemon

CMD ./install.sh && CompileDaemon -directory=./ -exclude=".#*" -exclude-dir=vendor
